title: A little bit of Vlad's
name: Vladimir Remar, Sysadmin, Musician
markdown: kramdown
url: https://vladimir-remar.github.io/
baseurl: '/vladimir-remar.github.io'
disqus_shortname: vladimirremar
author:
  name: 'Vladimir Remar'
  email: vladimir.remar@gmail.com
  twitter_username: vladimir_remar
  facebook_username: vladimir.remar
  github_username:  vladimir-remar
  linkedin_username:  vladimir.remar


permalink: /blog/:year/:month/:day/:title
